name: publish
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    name: Publish to github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go version
      - run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir -p $(go env GOPATH)/bin
          curl -L -o $(go env GOPATH)/bin/claat https://github.com/googlecodelabs/tools/releases/download/v2.2.0/claat-linux-amd64
          chmod +x $(go env GOPATH)/bin/claat
          claat version
          mkdir codelabs
          for f in `ls markdowns/*.md`; do claat export -o codelabs/ $f; done
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: |
          cd site
          npm install
          npm run dist
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "https://storage.googleapis.com/codelab-elements"
          replace: "https://openuc2.github.io/elements/codelab-elements"
          regex: false
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site/dist
          CLEAN: true

